version: '3'

services:
  client:
    container_name: client
    build: ./client/
    image: client
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app

  api:
    container_name: api
    build: ./api/
    image: api
    environment:
      TZ: 'Asia/Tokyo'
    ports:
      - '3003:3003'
      - '5555:5555'
    volumes:
      - ./api:/app
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: nest-db
      MYSQL_USER: nest-user
      MYSQL_PASSWORD: nest-pass
      MYSQL_ROOT_PASSWORD: nest-pass
      TZ: 'Asia/Tokyo'
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql

  nginx:
    depends_on:
      - client
      - api
    restart: always
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '3050:80'

volumes:
  db-data:
